services:
  # Main Backend API Service - Always Running
  - type: web
    name: kol-tracker-backend
    env: node
    plan: starter  # Starter plan for better reliability
    region: oregon
    buildCommand: |
      cd backend && npm install --production
    startCommand: cd backend && node keep-alive-wrapper.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: kol-tracker-db
          property: connectionString
      - key: JWT_SECRET
        value: 5c3b577c95b24f768d746a31229d79e0a5be87183c92e4bf504c4d88e2ae5957a90aa61e6900fd7425f739e3c5f44f5b84fa3554cadbccefb95e2223736669f8
      - key: TELETHON_URL
        fromService:
          type: web
          name: kol-tracker-telethon
          property: host
      - key: CORS_ORIGIN
        value: https://kolopz.com,https://www.kolopz.com,https://api.kolopz.com,https://telethon.kolopz.com
      - key: KEEP_ALIVE
        value: "true"
      - key: HEALTH_CHECK_INTERVAL
        value: "300000"
      - key: RESTART_ON_FAILURE
        value: "true"
    healthCheckPath: /api/health
    autoDeploy: true
    domains:
      - api.kolopz.com

  # Telethon Service - Always Running
  - type: web
    name: kol-tracker-telethon
    env: python
    plan: starter  # Starter plan for better reliability
    region: oregon
    buildCommand: |
      cd backend/telethon_service && 
      python -m pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: cd backend/telethon_service && python keep-alive-wrapper.py
    envVars:
      - key: API_ID
        value: 28152923
      - key: API_HASH
        value: 766760d2838474a5e6dd734d785aa7ad
      - key: SESSION_NAME
        value: telegram_session
      - key: DATABASE_URL
        fromDatabase:
          name: kol-tracker-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: BACKEND_URL
        fromService:
          type: web
          name: kol-tracker-backend
          property: host
      - key: KEEP_ALIVE
        value: "true"
      - key: HEALTH_CHECK_INTERVAL
        value: "300000"
      - key: RESTART_ON_FAILURE
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - telethon.kolopz.com
    disk:
      name: telethon-sessions
      mountPath: /opt/render/project/backend/telethon_service/sessions
      sizeGB: 1

# PostgreSQL Database - Reliable and fast
databases:
  - name: kol-tracker-db
    plan: free
    databaseName: kol_tracker_pro
    user: kol_user
    region: oregon 