services:
  - type: web
    name: kolnexus-backend
    env: node
    repo: https://github.com/Theepak90/kol-tracker-pro.git
    buildCommand: cd backend && npm install --legacy-peer-deps --production
    startCommand: cd backend && node simple-server.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://kolnexus.vercel.app,https://kolnexus2.netlify.app
    healthCheckPath: /api
    domains:
      - kolnexus-backend.onrender.com

  - type: web
    name: kolnexus-telethon
    env: python
    repo: https://github.com/Theepak90/kol-tracker-pro.git
    buildCommand: cd backend/telethon_service && pip install -r requirements.txt
    startCommand: cd backend/telethon_service && python main.py
    plan: free
    region: oregon
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_NAME
        value: telegram_session
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    domains:
      - kolnexus-telethon.onrender.com 