services:
  - type: web
    name: kol-tracker-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build:frontend && cd backend && npm install --legacy-peer-deps && npx nest build
    startCommand: node start-render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: kol-tracker-pro
      - key: JWT_SECRET
        sync: false
    disk:
      name: kol-tracker-disk
      mountPath: /opt/render/project/backend/dist
      sizeGB: 1

  - type: web
    name: kol-tracker-telethon
    env: python
    plan: free
    buildCommand: cd backend/telethon_service && pip install -r requirements.txt
    startCommand: cd backend/telethon_service && python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_NAME
        value: telegram_session
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: kol-tracker-pro
      - key: PORT
        value: 8000

# Database
databases:
  - name: kol-tracker-db
    databaseName: kol_tracker
    user: kol_user
    plan: free 