services:
  - type: web
    name: kolnexus-backend
    env: node
    repo: https://github.com/Theepak90/kol-tracker-pro.git
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start:prod
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://kolnexus.vercel.app,https://kolnexus2.netlify.app
    domains:
      - kolnexus-backend.onrender.com

  - type: web
    name: kolnexus-telethon
    env: python
    repo: https://github.com/Theepak90/kol-tracker-pro.git
    rootDir: backend/telethon_service
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    region: oregon
    envVars:
      - key: API_ID
        value: 28152923
      - key: API_HASH
        sync: false
      - key: SESSION_NAME
        value: telegram_session
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://kolnexus.vercel.app,https://kolnexus2.netlify.app
      - key: PORT
        value: 8000
    domains:
      - kolnexus-telethon.onrender.com 