services:
  # Full Stack Application Service
  - type: web
    name: kol-tracker-app
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: kol-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: TELETHON_SERVICE_URL
        value: https://kol-tracker-telethon.onrender.com
      - key: CORS_ORIGINS
        value: https://kol-tracker-app.onrender.com
    healthCheckPath: /api

  # Telethon Python Service
  - type: web
    name: kol-tracker-telethon
    env: python
    plan: free
    buildCommand: cd backend/telethon_service && pip install -r requirements.txt
    startCommand: cd backend/telethon_service && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_ID
        generateValue: true
      - key: API_HASH
        generateValue: true
      - key: SESSION_NAME
        value: telegram_session
      - key: MONGODB_URI
        fromDatabase:
          name: kol-tracker-db
          property: connectionString
      - key: PORT
        value: 8000
    healthCheckPath: /health

# Database
databases:
  - name: kol-tracker-db
    databaseName: kol_tracker
    user: kol_user
    plan: free 