services:
  - type: web
    name: kol-tracker-backend
    env: node
    repo: https://github.com/theepak/kol-tracker-pro.git
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb://localhost:27017/kol_tracker
      - key: PORT
        sync: false
    domains:
      - kol-tracker-backend.onrender.com 