services:
  - type: web
    name: kol-tracker-backend
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://kolnexus:your_password@cluster0.mongodb.net/kolnexus?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: LI/R0eeOaetvS7+M8QW+9vqVAJSItEbBFs33ywQWBe0=
    healthCheckPath: /api 